---
- name: Ensure docker is in a running state
  service:
    name: docker
    state: started
  register: dockerDetails
  until: dockerDetails.status.ActiveState == "active"
  retries: 15
  delay: 20

- name: Create app folder
  file:
    state: directory
    path: "{{ app_path }}"

- name: Clone pcdomanual site
  ansible.builtin.command: "git clone https://github.com/manualdousuario/pcdomanual-site.git {{ app_path }}/site"
  args:
    creates: "{{ app_path }}/site/.git"

- name: Automatically clone, pull and build pcdomanual site every hour
  ansible.builtin.cron:
    name: pull pcdomanual site
    special_time: hourly
    job: "git -C {{ app_path }}/site pull && hugo -s {{ app_path }}/site"

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml
    dest: "{{ app_path }}/docker-compose.yaml"

- name: Run docker-compose file
  community.docker.docker_compose:
    project_src: "{{ app_path }}/"
    state: present