---
- name: Ensure docker is in a running state
  service:
    name: docker
    state: started
  register: dockerDetails
  until: dockerDetails.status.ActiveState == "active"
  retries: 15
  delay: 20

- name: Create app folder
  file:
    state: directory
    path: "{{ app_path }}"

- name: Clone pcdomanual site
  ansible.builtin.git:
    repo: 'https://codeberg.org/manualdousuario/site.git'
    dest: "{{ app_path }}/site"
    version: "cd8ec45a9b5d4b533e271d54eb57c4301adf0502"

- name: Copy docker-compose file
  template:
    src: docker-compose.yaml
    dest: "{{ app_path }}/docker-compose.yaml"

- name: Run docker-compose file
  community.docker.docker_compose:
    project_src: "{{ app_path }}/"
    state: present