services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8.4
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS={{ docker_external_network_name }}
    networks:
      - {{ docker_external_network_name }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - "{{ app_path }}/site/public:/site"
    restart: unless-stopped
    labels:
      # hosts the main website
      caddy: "{{ domain }}"
      caddy.root: "* /site"
      caddy.file_server:

networks:
  {{ docker_external_network_name }}:
    external: true

volumes:
  caddy_data: