---
- name: Apply configuration to all hosts
  hosts: all
  gather_facts: yes
  roles:
    - role: common
      tags: common
    - role: reverse-proxy
      tags: reverse-proxy
    - role: nitter
      tags: nitter
    - role: observability
      tags: observability
    - role: miniflux
      tags: miniflux
    - role: libreddit
      tags: libreddit
    - role: linkding
      tags: linkding