---
- name: Apply configuration to all hosts
  hosts: all
  gather_facts: yes
  roles:
    - role: common
      tags: common
    - role: reverse-proxy
      tags: reverse-proxy
    - role: observability
      tags: observability
    - role: miniflux
      tags: miniflux
    - role: linkding
      tags: linkding
    - role: ladder
      tags: ladder