services:
  libreddit:
    build: https://github.com/libreddit/libreddit.git#v0.30.1
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks:
      - {{ docker_external_network_name }}
      - default
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--tries=1", "http://localhost:8080/settings"]
      interval: 10s
      timeout: 30s
    labels:
      caddy: "libreddit.{{ domain }}"
      caddy.reverse_proxy: {% raw %} "{{upstreams 8080}}" {% endraw %}

networks:
  {{ docker_external_network_name }}:
    external: true