services:
  shlink:
    image: shlinkio/shlink:3.7.0
    environment:
      DB_DRIVER: postgres
      DB_NAME: {{ SHLINK_POSTGRES_DATABASE }}
      DB_USER: {{ SHLINK_POSTGRES_USER }}
      DB_PASSWORD: {{ SHLINK_POSTGRES_PASSWORD }}
      DB_HOST: db
      DEFAULT_DOMAIN: "shlink.{{ domain }}"
      IS_HTTPS_ENABLED: "true"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - {{ docker_external_network_name }}
      - default
    restart: unless-stopped
    labels:
      caddy: "shlink.{{ domain }}"
      caddy.reverse_proxy.header_up_0: "-User-Agent"
      caddy.reverse_proxy: {% raw %} "{{upstreams 8080}}" {% endraw %}

  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: {{ SHLINK_POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ SHLINK_POSTGRES_PASSWORD }}
      POSTGRES_DB: {{ SHLINK_POSTGRES_DATABASE }}
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "{{ SHLINK_POSTGRES_USER }}", "-d", "{{ SHLINK_POSTGRES_DATABASE }}"]
      interval: 10s
      start_period: 30s

volumes:
  db:

networks:
  {{ docker_external_network_name }}:
    external: true
