services:
  linkding:
    image: ghcr.io/everywall/ladder:v0.0.21
    environment:
      PORT: 8080
      RULESET: https://raw.githubusercontent.com/everywall/ladder-rules/main/ruleset.yaml
    networks:
      - {{ docker_external_network_name }}
      - default
    restart: unless-stopped
    labels:
      caddy: "parede.{{ domain }}"
      caddy.reverse_proxy.header_up_0: "-User-Agent"
      caddy.reverse_proxy: {% raw %} "{{upstreams 8080}}" {% endraw %}

networks:
  {{ docker_external_network_name }}:
    external: true
