services:
  ots:
    build:
      context: https://github.com/Luzifer/ots.git#v1.11.1
    environment:
      REDIS_URL: redis://redis:6379/0
      SECRET_EXPIRY: '604800'
      STORAGE_TYPE: redis
      CUSTOMIZE: '/etc/customize.yaml'
    depends_on:
      - redis
    volumes:
      - ./customize.yaml:/etc/customize.yaml
    networks:
      - {{ docker_external_network_name }}
      - default
    restart: unless-stopped
    labels:
      caddy: "segredo.{{ domain }}"
      caddy.reverse_proxy.header_up_0: "-User-Agent"
      caddy.reverse_proxy: {% raw %} "{{upstreams 3000}}" {% endraw %}

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    # save a snapshot of the DB every 60 seconds if at least 1 write operation was performed
    # reduces loglevel since the --save generates a lot of logs
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - data:/data

volumes:
  data:

networks:
  {{ docker_external_network_name }}:
    external: true